### ISSUE TITLE
Javascript Highlighting Needs Work

### ISSUE THREAD

**Issue by KomodoKode** [ThatXliner/fall-syntax#12]
The Javascript syntax highlighting has little contrast, and is mostly green.

Also, ```function``` and ```for``` are both keywords, yet have different highlighting, which makes it look messy.

I suggest changing colors for keywords and class methods to improve the Javascript highlighting.

**Comment by ThatXliner** [comment]
Can you show me a screenshot of example JS code and ugly examples? Also, you can post in https://github.com/ThatXliner/fall-syntax/issues/6

**Comment by ThatXliner** [comment]
I wonder why var is green. Are you using master?

**Comment by KomodoKode** [comment]
Yeah I am on the master branch. But the highlighting still stays the same when I change branches.

**Comment by ThatXliner** [comment]
I cannot recreate on better-syn-highlight branch:
<img width="554" alt="Screen Shot 2021-01-02 at 12 16 42 PM" src="https://user-images.githubusercontent.com/66848002/103465864-61b64b00-4cf4-11eb-8c42-ec1b6d25ea49.png">

**Comment by KomodoKode** [comment]
I reloaded and the colors are different.
