### ISSUE TITLE
Better support for color blindness

### ISSUE THREAD

**Issue by ThatXliner** [ThatXliner/fall-syntax#14]

**Comment by KomodoKode** [comment]
I suggest making a custom version of the theme for color-blind simplicity. You can change the theme colors I have seen it on Atom UI/Syntax Theme READMEs.

**Comment by ThatXliner** [comment]
A specialized version of the theme? Not just improve the colors of this? Sure. "General usability" isn't a design point (although "look good" is one of them)

**Comment by KomodoKode** [comment]
This is the theme without any color :
<img width="638" alt="Theme without any color" src="https://user-images.githubusercontent.com/71739129/103715829-6be77c00-4f76-11eb-99e2-bfd75990ffe4.png">

**Comment by ThatXliner** [comment]
That's actually not as bad as I expected! The function/class definitions still contrasts!

**Comment by ThatXliner** [comment]
@KomodoKode You can pull request some tweaked colors.


Remember, the average dev workflow is:
`git clone`

`cd fall-syntax`

`apm link . --dev`

`<Open it in dev mode>`

**Comment by KomodoKode** [comment]
Got it, Thanks!
