### ISSUE TITLE
Need the hex codes c:

### ISSUE THREAD

**Issue by imnotril** [ThatXliner/fall-syntax#42]
It would be nice if you put a table with the colors in the README of the repository, or just share the colors (hexadecimal/rgb format), it is boring to look through the vscode theme files to find them. This way it could be much easier to port it to other editors, and would be more accurate than using a color picker.

nice color scheme btw

**Comment by imnotril** [comment]
+ i made a port to sublime text but I'm not very good with github, I don't know very well what to do, i have to do a fork adding the sublime text theme and then a pull request?

**Comment by ThatXliner** [comment]
https://github.com/ThatXliner/fall-syntax#color-palette
